/* The following code was generated by JFlex 1.4.3 on 3/21/16 5:26 PM */

package com.kgb.lisp.lexer;
import com.intellij.lexer.*;
import com.intellij.psi.tree.IElementType;
import static com.kgb.lisp.psi.LispTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 3/21/16 5:26 PM from the specification file
 * <tt>/home/k.betlej/workspace/idea-plugins/LispPlugin/src/com/kgb/lisp/lisp.flex</tt>
 */
public class LispLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\2\1\0\1\1\1\1\22\0\1\1\1\34\1\10"+
    "\4\0\1\37\1\15\1\16\1\32\1\30\1\0\1\31\1\7\1\33"+
    "\12\6\1\0\1\5\1\36\1\14\1\35\2\0\2\12\1\56\1\47"+
    "\1\50\1\51\13\12\1\54\1\52\1\53\1\55\5\12\1\0\1\11"+
    "\2\0\1\13\1\0\1\24\1\12\1\45\1\43\1\22\1\23\2\12"+
    "\1\27\2\12\1\25\1\42\1\26\1\40\1\41\1\46\1\20\1\3"+
    "\1\17\1\21\1\12\1\44\3\12\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\2\1\4\1\5\1\1"+
    "\1\6\1\7\1\10\1\11\6\6\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\5\6\2\3\1\6"+
    "\1\5\1\0\1\22\1\0\1\6\1\23\10\6\1\24"+
    "\1\25\2\6\1\26\12\6\1\27\1\30\2\6\1\31"+
    "\4\6\1\32\2\6\1\33\1\6\1\34\1\35\1\36"+
    "\1\37\1\6\1\40\1\41\6\6\1\42\1\6\1\43"+
    "\1\44\1\6\1\45\2\6\1\46\3\6\1\47\5\6"+
    "\1\50\2\6\1\51\2\6\1\52\3\6\1\53";

  private static int [] zzUnpackAction() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\u0149"+
    "\0\u0178\0\57\0\57\0\57\0\u01a7\0\u01d6\0\u0205\0\u0234"+
    "\0\u0263\0\u0292\0\57\0\57\0\57\0\57\0\57\0\57"+
    "\0\57\0\57\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac"+
    "\0\u03db\0\u040a\0\u0439\0\u0149\0\57\0\u0468\0\u0497\0\u0178"+
    "\0\u04c6\0\u04f5\0\u0524\0\u0553\0\u0582\0\u05b1\0\u05e0\0\u060f"+
    "\0\u0178\0\u0178\0\u063e\0\u066d\0\u069c\0\u06cb\0\u06fa\0\u0729"+
    "\0\u0758\0\u0787\0\u07b6\0\u07e5\0\u0814\0\u0843\0\u0872\0\u0178"+
    "\0\u0178\0\u08a1\0\u08d0\0\u0178\0\u08ff\0\u092e\0\u095d\0\u098c"+
    "\0\u0178\0\u09bb\0\u09ea\0\u0178\0\u0a19\0\u0178\0\u0178\0\u0178"+
    "\0\u0178\0\u0a48\0\u0178\0\u0178\0\u0a77\0\u0aa6\0\u0ad5\0\u0b04"+
    "\0\u0b33\0\u0b62\0\u0178\0\u0b91\0\u0178\0\u0178\0\u0bc0\0\u0178"+
    "\0\u0bef\0\u0c1e\0\u0178\0\u0c4d\0\u0c7c\0\u0cab\0\u0178\0\u0cda"+
    "\0\u0d09\0\u0d38\0\u0d67\0\u0d96\0\u0178\0\u0dc5\0\u0df4\0\u0178"+
    "\0\u0e23\0\u0e52\0\u0178\0\u0e81\0\u0eb0\0\u0edf\0\u0178";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\2\1\10"+
    "\1\2\1\11\1\2\1\12\1\13\1\14\1\15\1\11"+
    "\1\16\1\11\1\17\1\11\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\11"+
    "\1\33\1\11\1\34\1\35\1\36\1\11\1\37\7\11"+
    "\60\0\2\3\1\0\1\3\55\0\1\40\1\41\1\0"+
    "\1\11\3\0\2\11\3\0\3\11\1\42\5\11\1\0"+
    "\1\11\6\0\17\11\1\0\2\3\1\41\1\5\52\0"+
    "\2\6\1\0\54\6\6\0\1\7\1\43\47\0\10\44"+
    "\1\45\1\46\45\44\3\0\1\11\2\0\1\11\3\0"+
    "\2\11\3\0\11\11\1\0\1\11\6\0\17\11\3\0"+
    "\1\11\2\0\1\11\3\0\2\11\3\0\1\11\1\47"+
    "\7\11\1\0\1\11\6\0\1\50\16\11\3\0\1\11"+
    "\2\0\1\11\3\0\2\11\3\0\11\11\1\0\1\11"+
    "\6\0\1\11\1\51\15\11\3\0\1\11\2\0\1\11"+
    "\3\0\2\11\3\0\1\11\1\52\3\11\1\53\3\11"+
    "\1\0\1\11\6\0\1\54\16\11\3\0\1\11\2\0"+
    "\1\11\3\0\2\11\3\0\3\11\1\55\5\11\1\0"+
    "\1\11\6\0\1\56\16\11\3\0\1\11\2\0\1\11"+
    "\3\0\2\11\3\0\2\11\1\57\5\11\1\60\1\0"+
    "\1\11\6\0\17\11\3\0\1\11\2\0\1\11\3\0"+
    "\2\11\3\0\4\11\1\61\2\11\1\62\1\11\1\0"+
    "\1\11\6\0\17\11\3\0\1\11\2\0\1\11\3\0"+
    "\2\11\3\0\1\11\1\63\7\11\1\0\1\11\6\0"+
    "\17\11\3\0\1\11\2\0\1\11\3\0\2\11\3\0"+
    "\3\11\1\64\5\11\1\0\1\11\6\0\1\65\16\11"+
    "\3\0\1\11\2\0\1\11\3\0\2\11\3\0\1\11"+
    "\1\66\7\11\1\0\1\11\6\0\17\11\3\0\1\11"+
    "\2\0\1\11\3\0\2\11\3\0\5\11\1\67\3\11"+
    "\1\0\1\11\6\0\1\70\2\11\1\71\13\11\3\0"+
    "\1\11\2\0\1\11\3\0\2\11\3\0\11\11\1\0"+
    "\1\11\6\0\10\11\1\72\6\11\3\0\1\40\1\41"+
    "\1\0\1\11\3\0\2\11\3\0\11\11\1\0\1\11"+
    "\6\0\17\11\3\0\2\41\55\0\1\11\2\0\1\11"+
    "\3\0\2\11\3\0\1\73\10\11\1\0\1\11\6\0"+
    "\17\11\6\0\1\43\50\0\2\44\1\0\54\44\3\0"+
    "\1\11\2\0\1\11\3\0\2\11\3\0\2\11\1\74"+
    "\6\11\1\0\1\11\6\0\17\11\3\0\1\11\2\0"+
    "\1\11\3\0\2\11\3\0\1\75\10\11\1\0\1\11"+
    "\6\0\17\11\3\0\1\11\2\0\1\11\3\0\2\11"+
    "\3\0\11\11\1\0\1\11\6\0\1\76\16\11\3\0"+
    "\1\11\2\0\1\11\3\0\2\11\3\0\6\11\1\77"+
    "\2\11\1\0\1\11\6\0\17\11\3\0\1\11\2\0"+
    "\1\11\3\0\2\11\3\0\1\11\1\100\7\11\1\0"+
    "\1\11\6\0\17\11\3\0\1\11\2\0\1\11\3\0"+
    "\2\11\3\0\1\101\10\11\1\0\1\11\6\0\17\11"+
    "\3\0\1\11\2\0\1\11\3\0\2\11\3\0\11\11"+
    "\1\0\1\11\6\0\1\102\16\11\3\0\1\11\2\0"+
    "\1\11\3\0\2\11\3\0\6\11\1\103\2\11\1\0"+
    "\1\11\6\0\17\11\3\0\1\11\2\0\1\11\3\0"+
    "\2\11\3\0\6\11\1\104\2\11\1\0\1\11\6\0"+
    "\17\11\3\0\1\11\2\0\1\11\3\0\2\11\3\0"+
    "\10\11\1\105\1\0\1\11\6\0\17\11\3\0\1\11"+
    "\2\0\1\11\3\0\2\11\3\0\4\11\1\106\4\11"+
    "\1\0\1\11\6\0\17\11\3\0\1\11\2\0\1\11"+
    "\3\0\2\11\3\0\11\11\1\0\1\11\6\0\4\11"+
    "\1\107\12\11\3\0\1\11\2\0\1\11\3\0\2\11"+
    "\3\0\10\11\1\110\1\0\1\11\6\0\17\11\3\0"+
    "\1\11\2\0\1\11\3\0\2\11\3\0\1\11\1\111"+
    "\7\11\1\0\1\11\6\0\17\11\3\0\1\11\2\0"+
    "\1\11\3\0\2\11\3\0\6\11\1\112\1\113\1\11"+
    "\1\0\1\11\6\0\17\11\3\0\1\11\2\0\1\11"+
    "\3\0\2\11\3\0\1\11\1\114\7\11\1\0\1\11"+
    "\6\0\17\11\3\0\1\11\2\0\1\11\3\0\2\11"+
    "\3\0\11\11\1\0\1\11\6\0\11\11\1\115\5\11"+
    "\3\0\1\11\2\0\1\11\3\0\2\11\3\0\11\11"+
    "\1\0\1\11\6\0\6\11\1\116\10\11\3\0\1\11"+
    "\2\0\1\11\3\0\2\11\3\0\3\11\1\117\5\11"+
    "\1\0\1\11\6\0\17\11\3\0\1\11\2\0\1\11"+
    "\3\0\2\11\3\0\11\11\1\0\1\11\6\0\1\120"+
    "\16\11\3\0\1\11\2\0\1\11\3\0\2\11\3\0"+
    "\11\11\1\0\1\11\6\0\2\11\1\121\14\11\3\0"+
    "\1\122\2\0\1\11\3\0\2\11\3\0\11\11\1\0"+
    "\1\11\6\0\17\11\3\0\1\11\2\0\1\11\3\0"+
    "\2\11\3\0\11\11\1\0\1\11\6\0\1\11\1\123"+
    "\15\11\3\0\1\11\2\0\1\11\3\0\2\11\3\0"+
    "\6\11\1\124\2\11\1\0\1\11\6\0\17\11\3\0"+
    "\1\11\2\0\1\11\3\0\2\11\3\0\7\11\1\125"+
    "\1\11\1\0\1\11\6\0\17\11\3\0\1\11\2\0"+
    "\1\11\3\0\1\11\1\126\3\0\2\11\1\127\6\11"+
    "\1\0\1\11\6\0\17\11\3\0\1\11\2\0\1\11"+
    "\3\0\2\11\3\0\7\11\1\130\1\11\1\0\1\11"+
    "\6\0\17\11\3\0\1\11\2\0\1\11\3\0\2\11"+
    "\3\0\1\131\10\11\1\0\1\11\6\0\17\11\3\0"+
    "\1\11\2\0\1\11\3\0\2\11\3\0\6\11\1\132"+
    "\2\11\1\0\1\11\6\0\17\11\3\0\1\133\2\0"+
    "\1\11\3\0\2\11\3\0\11\11\1\0\1\11\6\0"+
    "\17\11\3\0\1\11\2\0\1\11\3\0\2\11\3\0"+
    "\11\11\1\0\1\11\6\0\12\11\1\134\4\11\3\0"+
    "\1\11\2\0\1\11\3\0\2\11\3\0\3\11\1\135"+
    "\5\11\1\0\1\11\6\0\17\11\3\0\1\11\2\0"+
    "\1\11\3\0\2\11\3\0\1\136\10\11\1\0\1\11"+
    "\6\0\17\11\3\0\1\137\2\0\1\11\3\0\2\11"+
    "\3\0\11\11\1\0\1\11\6\0\17\11\3\0\1\11"+
    "\2\0\1\11\3\0\2\11\3\0\7\11\1\140\1\11"+
    "\1\0\1\11\6\0\17\11\3\0\1\11\2\0\1\11"+
    "\3\0\2\11\3\0\1\141\3\11\1\142\4\11\1\0"+
    "\1\11\6\0\17\11\3\0\1\11\2\0\1\11\3\0"+
    "\2\11\3\0\3\11\1\143\5\11\1\0\1\11\6\0"+
    "\17\11\3\0\1\11\2\0\1\11\3\0\2\11\3\0"+
    "\3\11\1\144\5\11\1\0\1\11\6\0\17\11\3\0"+
    "\1\11\2\0\1\11\3\0\2\11\3\0\11\11\1\0"+
    "\1\11\6\0\13\11\1\145\3\11\3\0\1\11\2\0"+
    "\1\11\3\0\2\11\3\0\1\146\10\11\1\0\1\11"+
    "\6\0\17\11\3\0\1\11\2\0\1\11\3\0\2\11"+
    "\3\0\11\11\1\0\1\11\6\0\1\147\16\11\3\0"+
    "\1\11\2\0\1\11\3\0\2\11\3\0\1\11\1\150"+
    "\7\11\1\0\1\11\6\0\17\11\3\0\1\11\2\0"+
    "\1\11\3\0\2\11\3\0\11\11\1\0\1\11\6\0"+
    "\5\11\1\151\11\11\3\0\1\11\2\0\1\11\3\0"+
    "\2\11\3\0\11\11\1\0\1\11\6\0\14\11\1\152"+
    "\2\11\3\0\1\11\2\0\1\11\3\0\2\11\3\0"+
    "\1\11\1\153\7\11\1\0\1\11\6\0\17\11\3\0"+
    "\1\11\2\0\1\11\3\0\2\11\3\0\11\11\1\0"+
    "\1\11\6\0\1\154\16\11\3\0\1\11\2\0\1\11"+
    "\3\0\2\11\3\0\1\155\10\11\1\0\1\11\6\0"+
    "\17\11\3\0\1\11\2\0\1\11\3\0\2\11\3\0"+
    "\11\11\1\0\1\11\6\0\15\11\1\156\1\11\3\0"+
    "\1\11\2\0\1\11\3\0\2\11\3\0\2\11\1\157"+
    "\6\11\1\0\1\11\6\0\17\11\3\0\1\11\2\0"+
    "\1\11\3\0\2\11\3\0\11\11\1\0\1\11\6\0"+
    "\2\11\1\160\14\11\3\0\1\11\2\0\1\11\3\0"+
    "\2\11\3\0\11\11\1\0\1\11\6\0\16\11\1\161"+
    "\3\0\1\11\2\0\1\11\3\0\2\11\3\0\11\11"+
    "\1\0\1\11\6\0\5\11\1\162\11\11\3\0\1\11"+
    "\2\0\1\11\3\0\2\11\3\0\11\11\1\0\1\11"+
    "\6\0\13\11\1\163\3\11\3\0\1\11\2\0\1\11"+
    "\3\0\2\11\3\0\1\164\10\11\1\0\1\11\6\0"+
    "\17\11\3\0\1\11\2\0\1\11\3\0\2\11\3\0"+
    "\2\11\1\165\6\11\1\0\1\11\6\0\17\11\3\0"+
    "\1\11\2\0\1\11\3\0\2\11\3\0\1\11\1\166"+
    "\7\11\1\0\1\11\6\0\17\11\3\0\1\11\2\0"+
    "\1\11\3\0\2\11\3\0\3\11\1\167\5\11\1\0"+
    "\1\11\6\0\17\11";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3854];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\7\1\3\11\6\1\10\11\11\1\1\0"+
    "\1\11\1\0\121\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
  public LispLexer() {
    this((java.io.Reader)null);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LispLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 132) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 20: 
          { return IF;
          }
        case 44: break;
        case 38: 
          { return WRITE;
          }
        case 45: break;
        case 12: 
          { return OP_3;
          }
        case 46: break;
        case 15: 
          { return OP_6;
          }
        case 47: break;
        case 33: 
          { return IF_NULL;
          }
        case 48: break;
        case 26: 
          { return CAR;
          }
        case 49: break;
        case 3: 
          { return SPACE;
          }
        case 50: break;
        case 41: 
          { return DOWNFROM;
          }
        case 51: break;
        case 36: 
          { return PRINT;
          }
        case 52: break;
        case 5: 
          { return NUMBER;
          }
        case 53: break;
        case 35: 
          { return FALSE;
          }
        case 54: break;
        case 4: 
          { return COMMENT;
          }
        case 55: break;
        case 40: 
          { return COLLECT;
          }
        case 56: break;
        case 21: 
          { return IN;
          }
        case 57: break;
        case 8: 
          { return LP;
          }
        case 58: break;
        case 11: 
          { return OP_2;
          }
        case 59: break;
        case 14: 
          { return OP_5;
          }
        case 60: break;
        case 25: 
          { return NULL;
          }
        case 61: break;
        case 43: 
          { return DEF_STRUCTURE;
          }
        case 62: break;
        case 34: 
          { return CONS;
          }
        case 63: break;
        case 42: 
          { return DEFSTRUCT;
          }
        case 64: break;
        case 37: 
          { return DEFUN;
          }
        case 65: break;
        case 39: 
          { return DOWNTO;
          }
        case 66: break;
        case 30: 
          { return UPTO;
          }
        case 67: break;
        case 22: 
          { return DO;
          }
        case 68: break;
        case 9: 
          { return RP;
          }
        case 69: break;
        case 6: 
          { return PF_NAME;
          }
        case 70: break;
        case 31: 
          { return FROM;
          }
        case 71: break;
        case 10: 
          { return OP_1;
          }
        case 72: break;
        case 13: 
          { return OP_4;
          }
        case 73: break;
        case 16: 
          { return OP_7;
          }
        case 74: break;
        case 19: 
          { return TO;
          }
        case 75: break;
        case 24: 
          { return LET;
          }
        case 76: break;
        case 18: 
          { return STRING;
          }
        case 77: break;
        case 2: 
          { return com.intellij.psi.TokenType.WHITE_SPACE;
          }
        case 78: break;
        case 29: 
          { return TRUE;
          }
        case 79: break;
        case 23: 
          { return FOR;
          }
        case 80: break;
        case 17: 
          { return QV;
          }
        case 81: break;
        case 27: 
          { return CDR;
          }
        case 82: break;
        case 7: 
          { return EQ;
          }
        case 83: break;
        case 32: 
          { return LOOP;
          }
        case 84: break;
        case 1: 
          { return com.intellij.psi.TokenType.BAD_CHARACTER;
          }
        case 85: break;
        case 28: 
          { return SETQ;
          }
        case 86: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
