language: java
jdk: oraclejdk8
script: mvn -B clean package
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: hTdCeGKOWi/Frbo3v9mUBvu+9NMIcD9rQrpQHQVC6WfRFGk329XDwnbQ6tscaY8qS9Mw+CQuxF/M0kgjNT4Ib0pVYee8+pCcDCnqOZBEOiADSo+kSERKKCxMII/9u4o+w7mtuEADBo6u6SlxBTHM6+mpv+MTCX4lEhvuWAcVXlI=
  file: $CI_HOME/target/Lisp-IntelliJ-Plugin-bin.zip
  on:
    repo: labiod/lisp_idea_plugin
    tags: true
    all_branches: true
env:
  global:
  - GH_PROJECT_NAME: Lisp-IntelliJ-Plugin
  - GIT_AUTHOR_NAME: TravisCI
  - GIT_AUTHOR_EMAIL: noreply@travis-ci.org
  - CI_HOME=`pwd`
  - secure: EtVpVE54lkCGHxShrBXspb1dNZ0kgBgaiziWNLUlgt1dZx9yVrj4/dcc+OxHpjIoI/lxR/tNwZ5byPJCgYUdS8skjdPuqgf13dTh0Mi72M3xSF6q1D/K12YT5KT8qgJNqKxjm4fsIPcktFWPJAcZFRvKcEeeiSBdrnDgdrLIhSs=
